### ISSUE TITLE
PX4Flow i2c issue.

### ISSUE THREAD

**Issue by macgver** [eschnou/arduino-px4flow-i2c#1]
Hi there,

Im trying to add px4flow(Lucas-Kanade method custom firmware) to pixhawk(3.3rc1) I think, Its work :)  

My question:

1.Use USB connect PIX : I can in Mission Plannner's user items "opt_m_x" and "opt_m_y" for optical flow .

2.Use Battery powered : Can't in  Mission Plannner's user items "opt_m_x" and "opt_m_y" for optical flow. 

  But only reset PIX . I can in  Mission Plannner's user items "opt_m_x" and "opt_m_y" for optical flow.

**Comment by eschnou** [comment]
This question is not related to the arduino library. You should ask it directly on the https://github.com/PX4/Flow project or on the forum: https://groups.google.com/forum/#!forum/px4users

**Comment by eschnou** [comment]
But... I'm very interested by your work and would love to learn more. Have you posted some open source code ? Can you write a post with more details on the forum ? Would be great to share with the community !

**Comment by macgver** [comment]
Hi eschnou 
  OK. I have post to : diydrones.com.
 Thanks for your  reply.
