### ISSUE TITLE
position 

### ISSUE THREAD

**Issue by Eslam-Adel-Abouselima** [eschnou/arduino-px4flow-i2c#2]
can i get position x,y or velocity vx,vy without the ultrasonic ?

**Comment by eschnou** [comment]
No. The ground distance is required to be able to convert a motion in pixels to an absolut distance in meter per seconds. Without the sonar, the only information you'll have is the flow of pixels.

**Comment by Eslam-Adel-Abouselima** [comment]
Thanks
